name: Run Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev python3-dev xvfb ffmpeg
        sudo apt-get install alsa-utils alsa-oss

        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Upgrade pip and install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyaudio pydub googletrans torch vosk gdown pydrive2 coverage translate

    - name: Verify installation pyaudio and pydub 
      run: |
        python -m pip show pyaudio
        python -m pip show pydub

    - name: Run unit tests
      run: |
        xvfb-run -a coverage run -m unittest discover
        coverage xml

    - name: Coveralls
      uses: coverallsapp/github-action@v2
