name: Run Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install pyaudio
      run: |
        sudo apt-get install -y portaudio19-dev python3-dev xvfb ffmpeg

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install pip PyAudio
      run: |
        pip install pyaudio pydub
        
    - name: Verify installation pyaudio and pydub
      run: |
        python -m pip show pyaudio
        python -m pip show pydub


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        xvfb-run -a python -m unittest discover
        pip install -r requirements.txt
        
    - name: Run unit tests
      run: |
        coverage run -m unittest discover
        coverage xml


    - name: Coveralls
      uses: coverallsapp/github-action@v2
